services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
        required: true
    environment:
      DATABASE_URL: mysql://root:1234@database/my_database
    ports:
      - "5001:5000"
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
